

export const formStyles = {
  container: `max-w-2xl mx-auto`,
  backButton: `mr-4 p-2 rounded-md hover:bg-gray-100 transition-colors`,
  backIcon: `w-6 h-6 text-gray-600`,
  title: `text-2xl font-bold text-gray-800`,
  form: `bg-white rounded-lg shadow p-6`,
  formRow: `grid grid-cols-1 gap-6 mb-6`,
  formGroup: `space-y-2`,
  label: `block text-sm font-medium text-gray-700 mb-1`,
  input: `w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent`,
  textarea: `w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent`,
  select: `w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent`,
  buttonRow: `flex justify-end space-x-3`,
  cancelButton: `px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors`,
  saveButton: `px-4 py-2 bg-primary hover:bg-primary-dark text-white rounded-md transition-colors`,
  imageContainer: `flex items-center space-x-4`,
  imagePreview: `flex items-center justify-center w-16 h-16 border border-gray-300 rounded-md overflow-hidden bg-gray-100`,
  imagePreviewImg: `w-full h-full object-cover`,
  imageIcon: `w-8 h-8 text-gray-400`,
  imageButton: `cursor-pointer bg-primary hover:bg-primary-dark text-white px-4 py-2 rounded-md transition-colors`,
  deleteImageButton: `text-red-600 hover:text-red-800`,
  modalFooter: `flex justify-end space-x-3`,
  modalCancelButton: `px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors`,
  modalAcceptButton: `px-4 py-2 bg-primary hover:bg-primary-dark text-white rounded-md transition-colors`,
};